# SPDX-FileCopyrightText: 2026 Maria Eduarda W. M. Vianna <maria.vianna@grad.ufsc.br>
# SPDX-FileCopyrightText: 2026 Erico Souza Teixeira <erico.teixeira@venturus.org.br>
#
# SPDX-License-Identifier: Apache-2.0

"""Demonstration of Fermion-to-Qubit Mappings in Ket.

Compares the mapped qubit Hamiltonian generated by different mapping strategies
(Jordan-Wigner, Parity, Bravyi-Kitaev, and Symmetry-Conserving Bravyi-Kitaev)
for a simple fermionic hopping operator across a 4-qubit register.
"""

from ket import Process, FermionSentence, CreateFermion, AnnihilateFermion
from ket.chem import (
    jordan_wigner,
    parity,
    bravyi_kitaev,
    symmetry_conserving_bravyi_kitaev,
)


def main():
    p = Process()
    q = p.alloc(4)

    # 1. Simple hopping term: a^†_0 a_1
    op_hopping = CreateFermion(0) * AnnihilateFermion(1)

    print("=======================================================================")
    print(" DEMONSTRAÇÃO DE MAPEAMENTOS FÉRMION -> QUBIT NA PLATAFORMA KET")
    print(" Operador Fermiônico Simples: a⁺_0 a_1 (Hopping entre os orbitais 0 e 1)")
    print("=======================================================================\n")

    print("1. Jordan-Wigner (JW):")
    print("   Representação local de ocupação 1-para-1.")
    print("  ", jordan_wigner(op_hopping, q))
    print()

    print("2. Paridade (Parity):")
    print("   Representação baseada na paridade acumulada de ocupação.")
    print("  ", parity(op_hopping, q))
    print()

    print("3. Bravyi-Kitaev (BK - Árvore Adaptativa):")
    print("   Representação hierárquica baseada em Árvores de Fenwick (comprimento O(log N)).")
    print("  ", bravyi_kitaev(op_hopping, q, tree=True))
    print()

    # 2. Hopping term for SCBK (0->2 alpha, 1->3 beta)
    op_scbk = FermionSentence({
        CreateFermion(0) * AnnihilateFermion(2): 1.0,
        CreateFermion(1) * AnnihilateFermion(3): 1.0
    })

    print("4. Symmetry-Conserving Bravyi-Kitaev (SCBK):")
    print("   Árvore de Fenwick + Reordenação de Spin (α/β) + Eliminação de 2 Qubits de Simetria.")
    print("   (Registrador reduzido de 4 qubits para apenas 2 qubits!):")
    print("  ", symmetry_conserving_bravyi_kitaev(op_scbk, q, active_orbitals=4, n_alpha=1, n_beta=1))
    print("=======================================================================")


if __name__ == "__main__":
    main()
