# SPDX-FileCopyrightText: 2026 Maria Eduarda W. M. Vianna <maria.vianna@grad.ufsc.br>
# SPDX-FileCopyrightText: 2026 Erico Souza Teixeira <erico.teixeira@venturus.org.br>
#
# SPDX-License-Identifier: Apache-2.0

"""Validation tests comparing Ket's PySCF integration against OpenFermion.

Performs term-by-term and coefficient-by-coefficient comparisons
of qubit Hamiltonian generated by Ket (via Jordan-Wigner) against
OpenFermion for H2, LiH, BeH2, and H2O molecules.
"""

import sys
import os
import pytest
import numpy as np

# Ensure src/ is in python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../src")))

# Skip this entire test module cleanly if PySCF, OpenFermion, or openfermionpyscf is not installed
pyscf = pytest.importorskip("pyscf")
openfermion = pytest.importorskip("openfermion")
openfermionpyscf = pytest.importorskip("openfermionpyscf")

from openfermion import jordan_wigner as of_jw, get_fermion_operator
from openfermion.chem import MolecularData
from openfermionpyscf import run_pyscf

import ket
from ket.chem import fermionic_hamiltonian, jordan_wigner as ket_jw
from ket.base import Process


def _ket_hamiltonian_to_dict(h_ket):
    """Convert Ket qubit Hamiltonian into a canonical dict {pauli_string: coefficient}."""
    d = {}
    for term in h_ket.terms:
        clean_map = {q: p for q, p in term.map.items() if p != "I"}
        key = "I" if not clean_map else " ".join(f"{p}{q}" for q, p in sorted(clean_map.items()))
        d[key] = d.get(key, 0.0) + float(term.coef.real)
    return d


def _openfermion_hamiltonian_to_dict(h_of_qubit):
    """Convert OpenFermion QubitOperator into a canonical dict {pauli_string: coefficient}.

    Iterates through OpenFermion's qubit terms, converts term tuples (e.g. ((0, 'X'), (1, 'Z')))
    into sorted string keys ('X0 Z1'), and maps each key to its corresponding real coefficient.
    """
    of_dict = {}
    for term, coef in h_of_qubit.terms.items():
        if not term:
            key = "I"  # Pure scalar identity constant term
        else:
            # Format Pauli operators sorted by qubit index (e.g., 'X0 Z1 Y2')
            paulis = [f"{op}{q_idx}" for q_idx, op in term]
            paulis.sort(key=lambda x: int(x[1:]))
            key = " ".join(paulis)
        of_dict[key] = of_dict.get(key, 0.0) + float(coef.real)
    return of_dict


def _verify_ket_vs_openfermion(symbols, coordinates_angstrom, basis="sto-3g"):
    """Build Hamiltonian in Ket and compare terms and coefficients directly against OpenFermion (High-Level API)."""
    # --------------------------------------------------------------------------
    # Step 1: Generate Qubit Hamiltonian using Ket (High Level)
    # --------------------------------------------------------------------------
    h_fermion_ket = fermionic_hamiltonian(symbols, coordinates_angstrom, basis=basis)
    qubits_needed = max(op.orbital for term in h_fermion_ket for op in term.operators if term.operators) + 1
    
    p = Process()
    q = p.alloc(qubits_needed)
    h_qubit_ket = ket_jw(h_fermion_ket, q)
    ket_dict = _ket_hamiltonian_to_dict(h_qubit_ket)

    # --------------------------------------------------------------------------
    # Step 2: Generate Reference Qubit Hamiltonian using OpenFermion (High Level)
    # --------------------------------------------------------------------------
    # OpenFermion's MolecularData expects geometry as a list of tuples: [('H', (x, y, z)), ('H', (x, y, z))]
    geometry = [(sym, tuple(coords)) for sym, coords in zip(symbols, coordinates_angstrom)]
    
    # Initialize OpenFermion's MolecularData object (multiplicity=1 for singlet state, charge=0)
    molecule = MolecularData(geometry, basis=basis, multiplicity=1, charge=0)
    
    # Execute classical Restricted Hartree-Fock (RHF) calculation via OpenFermion's PySCF plugin
    molecule = run_pyscf(molecule, run_scf=True)
    
    # Extract the second-quantized InteractionOperator from the solved molecule object.
    # Note: InteractionOperator is OpenFermion's data structure that efficiently stores:
    #   - constant: nuclear repulsion energy (E_nuc)
    #   - one_body_tensor: 1-electron MO integrals h_pq
    #   - two_body_tensor: 2-electron MO integrals h_pqrs
    interaction_operator = molecule.get_molecular_hamiltonian()
    
    # Convert InteractionOperator (tensor representation) to FermionOperator (symbolic fermionic operators a+ and a)
    of_ferm = get_fermion_operator(interaction_operator)
    
    # Transform FermionOperator to QubitOperator via OpenFermion's Jordan-Wigner implementation
    of_qubit = of_jw(of_ferm)
    
    # Convert OpenFermion qubit Hamiltonian into a canonical Python dictionary {pauli_string: coefficient}
    of_dict = _openfermion_hamiltonian_to_dict(of_qubit)

    # --------------------------------------------------------------------------
    # Step 3: Assert Rigorous Term-by-Term, Magnitude, and Sign Equality
    # --------------------------------------------------------------------------
    assert len(ket_dict) == len(of_dict), (
        f"Term count mismatch: Ket={len(ket_dict)}, OpenFermion={len(of_dict)}"
    )

    for pauli_str, coef_ket in ket_dict.items():
        assert pauli_str in of_dict, f"Term '{pauli_str}' from Ket is missing in OpenFermion!"
        coef_of = of_dict[pauli_str]
        assert np.isclose(coef_ket, coef_of, atol=1e-5), (
            f"Coefficient mismatch for term '{pauli_str}': Ket={coef_ket:.8f}, OpenFermion={coef_of:.8f}"
        )


def test_h2_ket_vs_openfermion():
    """Build H2 Hamiltonian in Ket and compare terms and coefficients directly against OpenFermion."""
    _verify_ket_vs_openfermion(["H", "H"], [(0.0, 0.0, 0.0), (0.0, 0.0, 0.74)])


def test_lih_ket_vs_openfermion():
    """Build LiH Hamiltonian in Ket and compare terms and coefficients directly against OpenFermion."""
    _verify_ket_vs_openfermion(["Li", "H"], [(0.0, 0.0, 0.0), (0.0, 0.0, 1.595)])


def test_beh2_ket_vs_openfermion():
    """Build BeH2 Hamiltonian in Ket and compare terms and coefficients directly against OpenFermion."""
    _verify_ket_vs_openfermion(["H", "Be", "H"], [(0.0, 0.0, -1.326), (0.0, 0.0, 0.0), (0.0, 0.0, 1.326)])


def test_h2o_ket_vs_openfermion():
    """Build H2O Hamiltonian in Ket and compare terms and coefficients directly against OpenFermion."""
    _verify_ket_vs_openfermion(["O", "H", "H"], [(0.0, 0.0, 0.11779), (0.0, 0.755453, -0.471161), (0.0, -0.755453, -0.471161)])
